version: '3.7'
x-services-volume: &volume-dir
  type: bind
  source: .
  target: /usr/src/app

services:
  wallet1:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: 'sleepinglotus/wallet-dev'
    container_name: wallet1
    environment:
      - URL=http://wallet-nginx/wallet1
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
  wallet2:
    image: 'sleepinglotus/wallet-dev'
    container_name: wallet2
    environment:
      - URL=http://wallet-nginx/wallet2
    ports:
      - '3002:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
  wallet3:
    image: 'sleepinglotus/wallet-dev'
    container_name: wallet3
    environment:
      - URL=http://wallet-nginx/wallet3
    ports:
      - '3003:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
  nginx:
    image: 'sleepinglotus/wallet-nginx'
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx

    container_name: wallet-nginx
    restart: always
    depends_on:
      - wallet1
    ports:
      - '80:80'
networks:
  default:
    name: wallet_network_dev
